from django.urls import path, include
from . import views

urlpatterns = [ 
    #--------------------------------------------------- Admin -------------------------------------------------------------------
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('index',views.index,name='index'),
    path('change_password',views.change_password,name="change_password"),
    path('forget_pwd',views.forget_pwd,name='forget_pwd'),
    path('reset_pwd/<str:token>',views.reset_pwd,name='reset_pwd'),
    path('error_404',views.error_404,name='error_404'),
    path('success',views.success,name='success'),
    path('active_users',views.active_users,name='active_users'),
    path('blocked_users',views.blocked_users,name='blocked_users'),
    path('user_detail/<pk>',views.user_detail,name='user_detail'),
    path('user_block/<pk>',views.user_block,name='user_block'),
    path('user_active/<pk>',views.user_active,name='user_active'),
    path('user_delete/<pk>',views.user_delete,name='user_delete'),
    path('map/<pk>',views.map,name='map'),
    path('user_block_delete/<pk>',views.user_block_delete,name='user_block_delete'),
    path('view_all_subscriptions',views.view_all_subscriptions,name='view_all_subscriptions'),
    path('delete_subscription/<pk>',views.delete_subscription,name='delete_subscription'),
    path('edit_subscription/<pk>',views.edit_subscription,name='edit_subscription'),
    path('update_subscription',views.update_subscription,name='update_subscription'),
    path('add_subscriptions',views.add_subscriptions,name='add_subscriptions'),
    path('view_all_gifts',views.view_all_gifts,name='view_all_gifts'),
    path('view_all_faqs',views.view_all_faqs,name='view_all_faqs'),
    path('delete_faq/<pk>',views.delete_faq,name='delete_faq'),
    path('privacy_policy',views.privacy_policy,name='privacy_policy'),
    path('terms_and_conditions',views.terms_and_conditions,name='terms_and_conditions'),
    path('welcome',views.welcome,name='welcome'),
    path('matching',views.matching,name='matching'),
    path('admin_user_block',views.admin_user_block,name='admin_user_block'),
    path('admin_block',views.admin_block,name='admin_block'),
    path('admin_unblock',views.admin_unblock,name='admin_unblock'),
    path('admin_user_delete',views.admin_user_delete,name='admin_user_delete'),
    path('complains',views.complains,name='complains'),
    path('reply_complain',views.reply_complain,name='reply_complain'),
    path('app_stg',views.app_stg,name='app_stg'),
    path('app_links',views.app_links,name='app_links'),
    path('add_faqs',views.add_faqs,name='add_faqs'),
    path('update_link_android',views.update_link_android,name='update_link_android'),
    path('update_link_ios',views.update_link_ios,name='update_link_ios'),
    path('update_free_user_allowed_swipes',views.update_free_user_allowed_swipes,name='update_free_user_allowed_swipes'),
    path('update_free_user_swipes_time',views.update_free_user_swipes_time,name='update_free_user_swipes_time'),
    path('update_pro_user_allowed_swipes',views.update_pro_user_allowed_swipes,name='update_pro_user_allowed_swipes'),
    path('update_pro_user_swipes_time',views.update_pro_user_swipes_time,name='update_pro_user_swipes_time'),
    path('update_free_user_super_like_time',views.update_free_user_super_like_time,name='update_free_user_super_like_time'),
    path('update_free_user_allowed_super_like',views.update_free_user_allowed_super_like,name='update_free_user_allowed_super_like'),
    path('update_pro_user_super_like_time',views.update_pro_user_super_like_time,name='update_pro_user_super_like_time'),
    path('update_pro_user_allowed_super_like',views.update_pro_user_allowed_super_like,name='update_pro_user_allowed_super_like'),
    path('monthly_registration_chart', views.RegisterationChart, name="monthly_registration_chart"),
    path('monthly_earning_chart', views.EarningsChart, name="monthly_earning_chart"),
    path('today_earning', views.today_earning, name="today_earning"),
    path('total_earning', views.total_earning, name="total_earning"),
    path('pro_users', views.pro_users, name="pro_users"),
    path('free_users', views.free_users, name="free_users"),
    path('notification', views.notification, name="notification"),
    path('technical_issue_report', views.technical_issue_report, name="technical_issue_report"),
    path('reply_technical_issue_report', views.reply_technical_issue_report, name="reply_technical_issue_report"),
    path('billing_issue_report', views.billing_issue_report, name="billing_issue_report"),
    path('reply_billing_issue_report', views.reply_billing_issue_report, name="reply_billing_issue_report"),
    path('suggest', views.suggest, name="suggest"),
    path('reply_suggest', views.reply_suggest, name="reply_suggest"),
    path('ask_question', views.ask_question, name="ask_question"),
    path('reply_ask_question', views.reply_ask_question, name="reply_ask_question"),
    path('message', views.message, name="message"),
    path('terms_conditions', views.terms_conditions, name="terms_conditions"),
    path('privacypolicy', views.privacypolicy, name="privacypolicy"),

    #--------------------------------------------------- User -------------------------------------------------------------------

    path('confirm_email_msg/<str:token>', views.confirm_email_msg, name='confirm_email_msg'),
    path('change_forget_pwd/<str:token>', views.change_forget_pwd, name='change_forget_pwd'),
    path('user_change_email/<str:token>/<str:email>', views.user_change_email, name='user_change_email'),
    
]
