# Generated by Django 3.2.6 on 2022-01-05 12:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auto_msg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('welcome', models.TextField(max_length=255, null=True)),
                ('matching', models.TextField(max_length=255, null=True)),
                ('breakup', models.TextField(max_length=255, null=True)),
                ('user_block', models.TextField(max_length=255, null=True)),
                ('admin_block', models.TextField(max_length=255, null=True)),
                ('admin_unblock', models.TextField(max_length=255, null=True)),
                ('user_delete', models.TextField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(null=True)),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
