from django.urls import path
from . import views

urlpatterns = [
    path('email_exist',views.email_exist,name='email_exist'),
    path('phone_exist',views.phone_exist,name='phone_exist'),
    path('otp_email',views.otp_email,name='otp_email'),
    path('signup', views.signup, name='signup'),
    path('update_profile', views.update_profile, name='update_profile'),
    path('otp_phone', views.otp_phone, name='otp_phone'),
    path('verify_phone_no', views.verify_phone_no, name='verify_phone_no'),
    path('fb_social_login', views.fb_social_login, name='fb_social_login'),
    path('google_social_login', views.google_social_login, name='google_social_login'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('swipe_photo', views.swipe_photo, name='swipe_photo'),
    path('delete_photo', views.delete_photo, name='delete_photo'),
    path('location', views.location, name='location'),
    path('filter', views.filter, name='filter'),
    path('random_users',views.random_users,name='random_users'),
    path('like', views.like, name='like'),
    path('likes_list', views.likes_list, name='likes_list'),
    path('unlike', views.unlike, name='unlike'),
    path('liked_by_list', views.liked_by_list, name='liked_by_list'),
    path('dislike', views.dislike, name='dislike'),
    path('dislikes_list', views.dislikes_list, name='dislikes_list'),
    path('undislike', views.undislike, name='undislike'),
    path('favourite', views.favourite, name='favourite'),
    path('favourite_list', views.favourite_list, name='favourite_list'),
    path('unfavourite', views.unfavourite, name='unfavourite'),
    path('visited_list', views.visited_list, name='visited_list'),
    path('block', views.block, name='block'),
    path('block_list', views.block_list, name='block_list'),
    path('unblock', views.unblock, name='unblock'),
    path('report', views.report, name='report'),
    path('admin_report', views.admin_report, name='admin_report'),
    path('subscription', views.subscription, name='subscription'),
    path('change_email_otp_send', views.change_email_otp_send, name='change_email_otp_send'),
    path('update_email', views.update_email, name='update_email'),
    path('update_phone_no', views.update_phone_no, name='update_phone_no'),
    path('expo_token', views.expo_token, name='expo_token'),
    path('faqs', views.faqs, name='faqs'),
    path('left_likes', views.left_likes, name='left_likes'),
    path('packages', views.packages, name='packages'),
    path('package_detail', views.package_detail, name='package_detail'),
    path('cancel_subscription', views.cancel_subscription, name='cancel_subscription'),
    path('match_list', views.match_list, name='match_list'),
    path('unmatch', views.unmatch, name='unmatch'),
    path('block_from_chat', views.block_from_chat, name='block_from_chat'),
    path('instant_msg', views.instant_msg, name='instant_msg'),
    path('test', views.test)
]
